version: '3'
services:
  database:
    # postgres is an open source SQL RDBMS, target of "data ingestion" process
    ## Sample run command:
    ## $ docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
    image: postgres:9.5
    # restart: always
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
  s3-storage:
    # minio is an S3 compatible object store, local dev replacement for Ceph, for binary blob data (media and datasets)
    ## Sample run command:
    ## $ docker run -p 9000:9000 minio/minio server /data
    image: minio/minio
    command: server /data
    # restart: always
  elasticsearch:
    # elasticsearch is "You Know, for Search", backend to idigbio search API, target of "indexing" process
    ## Sample run command:
    ## $ docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    # restart: always
    environment:
      discovery.type: "single-node"